import pyautogui
from selenium import webdriver
import time
username = input("Username: ")
password = input("Password: ")
nameRepository = input("Repository Name: ")
fileName = input("File Name: ")
navegador = webdriver.Chrome()
navegador.get("https://github.com")
time.sleep(1.5)
navegador.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/div[2]/div[2]/a').click()
time.sleep(1.5)
navegador.find_element_by_xpath('//*[@id="login_field"]').click()
pyautogui.write(f'{username}')
time.sleep(1.5)
navegador.find_element_by_xpath('//*[@id="password"]').click()
pyautogui.write(f'{password}')
time.sleep(1.2)
navegador.find_element_by_xpath('//*[@id="login"]/div[4]/form/div/input[12]').click()
time.sleep(1.2)
navegador.find_element_by_xpath('//*[@id="repos-container"]/h2/a').click()
time.sleep(1.2)
navegador.find_element_by_xpath('//*[@id="repository_name"]').click()
pyautogui.write(f'{nameRepository}')
time.sleep(1.2)
navegador.find_element_by_xpath('//*[@id="new_repository"]/div[4]/button').click()
time.sleep(1)
navegador.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/git-clone-help/div[1]/p/a[2]').click()
time.sleep(1.5)
pyautogui.moveTo(960, 540)
pyautogui.leftClick()
time.sleep(1.3)
pyautogui.moveTo(580, 335)
pyautogui.leftClick()
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('down')
time.sleep(1.3)
pyautogui.press('down')
time.sleep(1.3)
pyautogui.press('down')
time.sleep(1.3)
pyautogui.press('enter')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
pyautogui.write(f'{fileName}')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('tab')
time.sleep(1.3)
pyautogui.press('enter')
time.sleep(2.5)
navegador.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/form/button').click()


